<div class="row">
	<div class="col-xs-12">
		<form method="post" class="form-horizontal" role="form">
			<?php foreach($this->formFields as $name => $label): ?>
				<div class="form-group">
					<label for="<?= $name ?>" class="col-sm-2 control-label"><?= $label ?></label>
					<div class="col-sm-10">
					<?php if($name == 'USUARIO'): ?>
						<select class="form-control" name="<?= $name ?>">
							<?php foreach($this->users as $user): ?>
								<option value="<?= $user->NOMEUSUARIO ?>"><?= $user->NOMECOMPLETO ?></option>
							<?php endforeach ?>
						</select>
					<?php else: ?>
						<input type="text" class="form-control" name="<?= $name ?>"/>
					<?php endif ?>
					</div>
				</div>
			<?php endforeach ?>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-primary">Adicionar</button>
				</div>
			</div>
		</form>
	</div>
</div>