<div class="row">
	<div class="col-xs-12">
		<form method="post" class="form-horizontal" role="form">
			<?php foreach($this->formFields as $name => $label): ?>
				<div class="form-group">
					<label for="<?= $name ?>" class="col-sm-2 control-label"><?= $label ?></label>
					<div class="col-sm-10">
						<input type="text" class="form-control" name="<?= $name ?>" value="<?= $this->entry->$name ?: '' ?>"/>
					</div>
				</div>
			<?php endforeach ?>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-primary">Salvar</button>
					<a class="btn btn-primary" href="<?= $this->url('cartaocredito', 'index') ?>">Voltar</a>
				</div>
			</div>
		</form>
	</div>
</div>
