<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap 101 Template</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="img/facicon.png" rel="shortcut icon">
    <link href="css/style.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

  	<header class="container">
  		<div class="row">
  			<div class="col-xs-12">
  				<h1 class="text-center">Trabalho de BD</h1>
  			</div>
  		</div>
  	</header>

  	<div class="container">
    	<?php require $this->_viewFilename ?>
    </div>

    <footer class="container">
    	<div class="row">
    		<div class="col-xs-6">
    			<h3>Tecnologias</h3>
    			<ul>
    				<li>PHP 5.4+</li>
    				<li>MySQL</li>
    				<li>Apache 2.2</li>
    			</ul>
    		</div>
    		<div class="col-xs-6">
    			<h3>Grupo</h3>
    			<ul>
    				<li>Rafael Andreatta Martins <small>#USP 7564019</small></li>
    				<li>Elias Rodrigues <small>#USP x</small></li>
    				<li>Rodolfo <small>#USP x</small></li>
    				<li>Vinicius Katata <small>#USP x</small></li>
    			</ul>
    		</div>
    	</div>
    </footer>

    <script src="js/script.min.js"></script>
  </body>
</html>